name: Build and Release

on:
  push:
    branches: [main, master]  # Se ejecutará en cualquiera de estas ramas principales
    paths:
      - 'APP/**'  # Solo se ejecuta cuando hay cambios en la carpeta APP

# Agregar permisos explícitos para crear releases
permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './APP/package.json'

      - name: Install dependencies
        working-directory: ./APP
        run: npm install

      - name: Build application
        working-directory: ./APP
        run: npm run build:win

      - name: Generate Release Name
        id: release_name
        shell: bash
        run: |
          echo "RELEASE_NAME=$(date +'%Y%m%d')_$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: build_${{ env.RELEASE_NAME }}
          name: Build ${{ env.RELEASE_NAME }}
          draft: false
          prerelease: false
          files: |
            ./APP/dist/*.exe
